version: '3.8'

services:
  service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../../:/src
    working_dir: "/src"
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - network
networks:
  network:
    driver: bridge